//-|                                             ;
//-|            PRIMITIVE DATA TYPES             ;
//-|             {Primitive Types}               ;
//-|                                             ;
//: Stored in execution context <= call stack    ;
//-|                                             ;
//> 1. Number                                    ;
//> 2. String                                    ;
//> 3. Boolean                                   ;
//> 4. Undefined                                 ;
//> 5. Null                                      ;
//> 6. Symbol                                    ;
//> 7. BigInt                                    ;
//>                                              ;
//-|                                             ;
//-|                 OBJECTS                     ;
//-|            {Reference Types}                ;
//-|                                             ;
//: Stored in the Heap, referenced in  call stack;
//>                                              ;
//> 1. Object Literal                            ;
//> 2. Arrays                                    ;
//> 3. Functions                                 ;
//> 4. Many more ?                               ;
//>                                              ;
//* These are stored in the memory differently   ;
//-|                                             ;
//-|           Prototype Inheritance             ;
//-|                                             ;
//>   {Object Oriented Programming OOP With J}   ;
//> 1. ;
//> 2. ;
//> 3. ;
//-|                                             ;
//-|                EVENT LOOP                   ;
//-|         {Asynchronous JavaScript}           ;
//-|                                             ;
//> 1. Promises = ;
//> 2. Async/Await = ;
//> 3. AJAX = ;
//-|                                             ;
//-|         How the DOM Really Works            ;
//-|              {DOM & EVENTS}                 ;
//-|                                             ;
//> 1. ;
//> 2. ;

// K6KRV24-LLAAJMM-X7U3AKK-E6YEZKQ
